version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: peralava979
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - '5432:5432'
  app:
    build: .
    command: npm start
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_PASSWORD: peralava979
      POSTGRES_USER: postgres
      POSTGRES_DB: db
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
   
